<template>
    <div>
        <nav class="title">滚动区块</nav>
        <div class="singer" ref="singer">
            <index-list :data="items" ref="list">
                <ul>
                    <li v-for="group in items" class="list-group" ref="listGroup">
                        <h2 class="list-group-title">{{group.title}}</h2>
                        <uL>
                            <li @click="selectItem(item)" v-for="item in group.items" class="list-group-item">
                                <span class="name">{{item.name}}</span>
                            </li>
                        </uL>
                    </li>
                </ul>
            </index-list>
        </div>
    </div>
</template>

<script type="text/ecmascript-6">
    const HOT_SINGER_LEN = 10
    const HOT_NAME = '热门'

    export default {
        data() {
            return {
                items: []
            }
        },
        created() {
            this._getSingerList()
        },
        methods: {
            // 选中一项
            selectItem(item) {
                console.log(item)
            },
            _getSingerList() {
                setTimeout(() => {
                    this.items = this._normalizeItems([
                        {
                            "Farea": "1",
                            "Findex": "X",
                            "Fsinger_id": "5062",
                            "Fsinger_name": "薛之谦",
                            "Fsinger_tag": "541,555",
                            "Fsort": "1",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "4558",
                            "Fsinger_name": "周杰伦",
                            "Fsinger_tag": "541,555",
                            "Fsort": "2",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "2",
                            "Findex": "B",
                            "Fsinger_id": "11733",
                            "Fsinger_name": "BIGBANG (빅뱅)",
                            "Fsinger_tag": "645,663,676,679,694,703,710,713",
                            "Fsort": "3",
                            "Ftrend": "0",
                            "Ftype": "2",
                        }, {
                            "Farea": "0",
                            "Findex": "C",
                            "Fsinger_id": "143",
                            "Fsinger_name": "陈奕迅",
                            "Fsinger_tag": "555",
                            "Fsort": "4",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "L",
                            "Fsinger_id": "4286",
                            "Fsinger_name": "林俊杰",
                            "Fsinger_tag": "541,555",
                            "Fsort": "5",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "3",
                            "Findex": "A",
                            "Fsinger_id": "944940",
                            "Fsinger_name": "Alan Walker (艾伦·沃克)",
                            "Fsinger_tag": "",
                            "Fsort": "6",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "L",
                            "Fsinger_id": "60505",
                            "Fsinger_name": "李荣浩",
                            "Fsinger_tag": "",
                            "Fsort": "7",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "T",
                            "Fsinger_id": "34412",
                            "Fsinger_name": "TFBOYS",
                            "Fsinger_tag": "",
                            "Fsort": "8",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "3",
                            "Findex": "M",
                            "Fsinger_id": "4983",
                            "Fsinger_name": "Maroon 5 (魔力红乐团)",
                            "Fsinger_tag": "644,645",
                            "Fsort": "9",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "X",
                            "Fsinger_id": "7221",
                            "Fsinger_name": "许嵩",
                            "Fsinger_tag": "",
                            "Fsort": "10",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "G",
                            "Fsinger_id": "13948",
                            "Fsinger_name": "G.E.M. 邓紫棋",
                            "Fsinger_tag": "541,555",
                            "Fsort": "11",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "6499",
                            "Fsinger_name": "张杰",
                            "Fsinger_tag": "555",
                            "Fsort": "12",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "L",
                            "Fsinger_id": "204664",
                            "Fsinger_name": "鹿晗",
                            "Fsinger_tag": "",
                            "Fsort": "13",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "89698",
                            "Fsinger_name": "庄心妍",
                            "Fsinger_tag": "555",
                            "Fsort": "14",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "Y",
                            "Fsinger_id": "11608",
                            "Fsinger_name": "杨宗纬",
                            "Fsinger_tag": "555",
                            "Fsort": "15",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "3",
                            "Findex": "J",
                            "Fsinger_id": "16257",
                            "Fsinger_name": "Justin Bieber (贾斯汀·比伯)",
                            "Fsinger_tag": "645,710",
                            "Fsort": "16",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "199515",
                            "Fsinger_name": "张碧晨",
                            "Fsinger_tag": "",
                            "Fsort": "17",
                            "Ftrend": "-1",
                            "Ftype": "1",
                            "voc": "1"
                        }, {
                            "Farea": "1",
                            "Findex": "H",
                            "Fsinger_id": "163550",
                            "Fsinger_name": "华晨宇",
                            "Fsinger_tag": "555",
                            "Fsort": "18",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "174",
                            "Fsinger_name": "张学友",
                            "Fsinger_tag": "555",
                            "Fsort": "19",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "T",
                            "Fsinger_id": "4701",
                            "Fsinger_name": "田馥甄",
                            "Fsinger_tag": "555",
                            "Fsort": "20",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "2",
                            "Findex": "R",
                            "Fsinger_id": "9962",
                            "Fsinger_name": "RADWIMPS (ラッドウィンプス)",
                            "Fsinger_tag": "645,683,690,709",
                            "Fsort": "21",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "0",
                            "Findex": "X",
                            "Fsinger_id": "13203",
                            "Fsinger_name": "萧敬腾",
                            "Fsinger_tag": "",
                            "Fsort": "22",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "N",
                            "Fsinger_id": "137",
                            "Fsinger_name": "那英",
                            "Fsinger_tag": "555",
                            "Fsort": "23",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "W",
                            "Fsinger_id": "265",
                            "Fsinger_name": "王力宏",
                            "Fsinger_tag": "541,573",
                            "Fsort": "24",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "4607",
                            "Fsinger_name": "张靓颖",
                            "Fsinger_tag": "555",
                            "Fsort": "25",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "W",
                            "Fsinger_id": "180646",
                            "Fsinger_name": "吴亦凡",
                            "Fsinger_tag": "",
                            "Fsort": "26",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "B",
                            "Fsinger_id": "2",
                            "Fsinger_name": "BEYOND",
                            "Fsinger_tag": "541,558,569",
                            "Fsort": "27",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "0",
                            "Findex": "L",
                            "Fsinger_id": "11606",
                            "Fsinger_name": "林宥嘉",
                            "Fsinger_tag": "555",
                            "Fsort": "28",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "N",
                            "Fsinger_id": "69205",
                            "Fsinger_name": "南征北战",
                            "Fsinger_tag": "",
                            "Fsort": "29",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "W",
                            "Fsinger_id": "3954",
                            "Fsinger_name": "汪苏泷",
                            "Fsinger_tag": "541,555,562",
                            "Fsort": "30",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "2",
                            "Findex": "G",
                            "Fsinger_id": "19851",
                            "Fsinger_name": "G-DRAGON (权志龙)",
                            "Fsinger_tag": "646,663,666,676,679,690,705,714",
                            "Fsort": "31",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "S",
                            "Fsinger_id": "5924",
                            "Fsinger_name": "苏打绿",
                            "Fsinger_tag": "544,555,569",
                            "Fsort": "32",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "P",
                            "Fsinger_id": "4442",
                            "Fsinger_name": "朴树",
                            "Fsinger_tag": "541,555,558",
                            "Fsort": "33",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "W",
                            "Fsinger_id": "264",
                            "Fsinger_name": "王菲",
                            "Fsinger_tag": "555",
                            "Fsort": "34",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "K",
                            "Fsinger_id": "11761",
                            "Fsinger_name": "筷子兄弟",
                            "Fsinger_tag": "555",
                            "Fsort": "35",
                            "Ftrend": "-1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "M",
                            "Fsinger_id": "160022",
                            "Fsinger_name": "MC天佑",
                            "Fsinger_tag": "",
                            "Fsort": "36",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "M",
                            "Fsinger_id": "1045852",
                            "Fsinger_name": "MC魏小然",
                            "Fsinger_tag": "",
                            "Fsort": "37",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "J",
                            "Fsinger_id": "12111",
                            "Fsinger_name": "金志文",
                            "Fsinger_tag": "541,555",
                            "Fsort": "40",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "S",
                            "Fsinger_id": "22874",
                            "Fsinger_name": "孙子涵",
                            "Fsinger_tag": "541,555,562",
                            "Fsort": "41",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "A",
                            "Fsinger_id": "6028",
                            "Fsinger_name": "A-Lin",
                            "Fsinger_tag": "555",
                            "Fsort": "42",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "X",
                            "Fsinger_id": "3376",
                            "Fsinger_name": "许巍",
                            "Fsinger_tag": "541,558",
                            "Fsort": "43",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "S",
                            "Fsinger_id": "61620",
                            "Fsinger_name": "宋冬野",
                            "Fsinger_tag": "544,558",
                            "Fsort": "45",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "141",
                            "Fsinger_name": "张惠妹",
                            "Fsinger_tag": "555",
                            "Fsort": "46",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "4365",
                            "Fsinger_name": "周传雄",
                            "Fsinger_tag": "541,555",
                            "Fsort": "47",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "167",
                            "Fsinger_name": "张信哲",
                            "Fsinger_tag": "555",
                            "Fsort": "48",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Y",
                            "Fsinger_id": "944274",
                            "Fsinger_name": "杨洋",
                            "Fsinger_tag": "",
                            "Fsort": "49",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "X",
                            "Fsinger_id": "22704",
                            "Fsinger_name": "徐良",
                            "Fsinger_tag": "541,562",
                            "Fsort": "50",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "C",
                            "Fsinger_id": "4284",
                            "Fsinger_name": "陈小春",
                            "Fsinger_tag": "555",
                            "Fsort": "51",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Q",
                            "Fsinger_id": "34703",
                            "Fsinger_name": "曲婉婷",
                            "Fsinger_tag": "",
                            "Fsort": "52",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "P",
                            "Fsinger_id": "1102711",
                            "Fsinger_name": "鹏泊",
                            "Fsinger_tag": "",
                            "Fsort": "53",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "S",
                            "Fsinger_id": "109",
                            "Fsinger_name": "孙燕姿",
                            "Fsinger_tag": "555,558",
                            "Fsort": "54",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "3",
                            "Findex": "W",
                            "Fsinger_id": "12978",
                            "Fsinger_name": "Wiz Khalifa (维兹·卡利法)",
                            "Fsinger_tag": "644",
                            "Fsort": "55",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "168",
                            "Fsinger_name": "张宇",
                            "Fsinger_tag": "555",
                            "Fsort": "56",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "G",
                            "Fsinger_id": "61959",
                            "Fsinger_name": "葛林",
                            "Fsinger_tag": "",
                            "Fsort": "58",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "M",
                            "Fsinger_id": "54",
                            "Fsinger_name": "莫文蔚",
                            "Fsinger_tag": "555",
                            "Fsort": "59",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "1012038",
                            "Fsinger_name": "张磊",
                            "Fsinger_tag": "",
                            "Fsort": "60",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "J",
                            "Fsinger_id": "1041231",
                            "Fsinger_name": "Jam",
                            "Fsinger_tag": "",
                            "Fsort": "61",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "N",
                            "Fsinger_id": "4422",
                            "Fsinger_name": "牛奶咖啡",
                            "Fsinger_tag": "552,555",
                            "Fsort": "62",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "W",
                            "Fsinger_id": "4604",
                            "Fsinger_name": "汪峰",
                            "Fsinger_tag": "541,555,569",
                            "Fsort": "63",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "3",
                            "Findex": "C",
                            "Fsinger_id": "39000",
                            "Fsinger_name": "Charlie Puth (查理·普斯)",
                            "Fsinger_tag": "644",
                            "Fsort": "64",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "B",
                            "Fsinger_id": "4545",
                            "Fsinger_name": "本兮",
                            "Fsinger_tag": "",
                            "Fsort": "65",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "H",
                            "Fsinger_id": "24833",
                            "Fsinger_name": "胡夏",
                            "Fsinger_tag": "555",
                            "Fsort": "66",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "M",
                            "Fsinger_id": "28227",
                            "Fsinger_name": "马旭东",
                            "Fsinger_tag": "555",
                            "Fsort": "67",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "W",
                            "Fsinger_id": "38625",
                            "Fsinger_name": "威仔",
                            "Fsinger_tag": "",
                            "Fsort": "68",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "L",
                            "Fsinger_id": "11707",
                            "Fsinger_name": "李易峰",
                            "Fsinger_tag": "555",
                            "Fsort": "70",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Y",
                            "Fsinger_id": "7485",
                            "Fsinger_name": "雨宗林",
                            "Fsinger_tag": "555",
                            "Fsort": "71",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "G",
                            "Fsinger_id": "11626",
                            "Fsinger_name": "郭静",
                            "Fsinger_tag": "555",
                            "Fsort": "72",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "L",
                            "Fsinger_id": "4615",
                            "Fsinger_name": "李宇春",
                            "Fsinger_tag": "555",
                            "Fsort": "73",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "224",
                            "Fsinger_name": "张韶涵",
                            "Fsinger_tag": "555",
                            "Fsort": "74",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "M",
                            "Fsinger_id": "943468",
                            "Fsinger_name": "萌萌哒天团",
                            "Fsinger_tag": "",
                            "Fsort": "75",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "3",
                            "Findex": "F",
                            "Fsinger_id": "4868",
                            "Fsinger_name": "Fall Out Boy (打倒男孩)",
                            "Fsinger_tag": "645",
                            "Fsort": "76",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "3",
                            "Findex": "R",
                            "Fsinger_id": "6966",
                            "Fsinger_name": "Rihanna (蕾哈娜)",
                            "Fsinger_tag": "710",
                            "Fsort": "77",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "3",
                            "Findex": "T",
                            "Fsinger_id": "156095",
                            "Fsinger_name": "The Chainsmokers (烟民二人组)",
                            "Fsinger_tag": "",
                            "Fsort": "78",
                            "Ftrend": "-1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "X",
                            "Fsinger_id": "23800",
                            "Fsinger_name": "夏婉安",
                            "Fsinger_tag": "",
                            "Fsort": "79",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "968571",
                            "Fsinger_name": "周二珂",
                            "Fsinger_tag": "",
                            "Fsort": "80",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "3",
                            "Findex": "T",
                            "Fsinger_id": "947788",
                            "Fsinger_name": "Tez Cadey",
                            "Fsinger_tag": "",
                            "Fsort": "81",
                            "Ftrend": "0",
                            "Ftype": "0",
                        }, {
                            "Farea": "3",
                            "Findex": "E",
                            "Fsinger_id": "4880",
                            "Fsinger_name": "Eminem (艾米纳姆)",
                            "Fsinger_tag": "645,647",
                            "Fsort": "82",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "Z",
                            "Fsinger_id": "219",
                            "Fsinger_name": "张敬轩",
                            "Fsinger_tag": "541,555",
                            "Fsort": "83",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Q",
                            "Fsinger_id": "1042260",
                            "Fsinger_name": "齐一",
                            "Fsinger_tag": "",
                            "Fsort": "84",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "H",
                            "Fsinger_id": "1043567",
                            "Fsinger_name": "韩安旭",
                            "Fsinger_tag": "",
                            "Fsort": "85",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "L",
                            "Fsinger_id": "38",
                            "Fsinger_name": "李圣杰",
                            "Fsinger_tag": "555,562",
                            "Fsort": "86",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Z",
                            "Fsinger_id": "63938",
                            "Fsinger_name": "张赫宣",
                            "Fsinger_tag": "",
                            "Fsort": "87",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "2",
                            "Findex": "9",
                            "Fsinger_id": "162691",
                            "Fsinger_name": "방탄소년단 (防弹少年团)",
                            "Fsinger_tag": "536,678,663,676",
                            "Fsort": "88",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "L",
                            "Fsinger_id": "161444",
                            "Fsinger_name": "刘瑞琦",
                            "Fsinger_tag": "555",
                            "Fsort": "89",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "3",
                            "Findex": "A",
                            "Fsinger_id": "12578",
                            "Fsinger_name": "Adele (阿黛尔)",
                            "Fsinger_tag": "644",
                            "Fsort": "90",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "S",
                            "Fsinger_id": "1011983",
                            "Fsinger_name": "双笙",
                            "Fsinger_tag": "",
                            "Fsort": "91",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "T",
                            "Fsinger_id": "15514",
                            "Fsinger_name": "逃跑计划",
                            "Fsinger_tag": "544,569",
                            "Fsort": "92",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "2",
                            "Findex": "B",
                            "Fsinger_id": "1190986",
                            "Fsinger_name": "BLACKPINK",
                            "Fsinger_tag": "",
                            "Fsort": "93",
                            "Ftrend": "0",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "Y",
                            "Fsinger_id": "198135",
                            "Fsinger_name": "易烊千玺",
                            "Fsinger_tag": "",
                            "Fsort": "94",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "3",
                            "Findex": "O",
                            "Fsinger_id": "12926",
                            "Fsinger_name": "Owl City (猫头鹰之城)",
                            "Fsinger_tag": "644",
                            "Fsort": "95",
                            "Ftrend": "1",
                            "Ftype": "2",
                        }, {
                            "Farea": "1",
                            "Findex": "T",
                            "Fsinger_id": "6370",
                            "Fsinger_name": "谭晶",
                            "Fsinger_tag": "",
                            "Fsort": "96",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "C",
                            "Fsinger_id": "22926",
                            "Fsinger_name": "陈翔",
                            "Fsinger_tag": "555",
                            "Fsort": "97",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }, {
                            "Farea": "0",
                            "Findex": "L",
                            "Fsinger_id": "163",
                            "Fsinger_name": "刘德华",
                            "Fsinger_tag": "555",
                            "Fsort": "98",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "3",
                            "Findex": "O",
                            "Fsinger_id": "24561",
                            "Fsinger_name": "One Direction (单向组合)",
                            "Fsinger_tag": "645",
                            "Fsort": "99",
                            "Ftrend": "0",
                            "Ftype": "2",
                        }, {
                            "Farea": "0",
                            "Findex": "C",
                            "Fsinger_id": "112",
                            "Fsinger_name": "蔡健雅",
                            "Fsinger_tag": "541,555",
                            "Fsort": "100",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "F",
                            "Fsinger_id": "4351",
                            "Fsinger_name": "范玮琪",
                            "Fsinger_tag": "541,555,558",
                            "Fsort": "101",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "X",
                            "Fsinger_id": "16244",
                            "Fsinger_name": "徐佳莹",
                            "Fsinger_tag": "541,555,569",
                            "Fsort": "102",
                            "Ftrend": "1",
                            "Ftype": "1",
                        }, {
                            "Farea": "1",
                            "Findex": "J",
                            "Fsinger_id": "44018",
                            "Fsinger_name": "金南玲",
                            "Fsinger_tag": "",
                            "Fsort": "103",
                            "Ftrend": "-1",
                            "Ftype": "1",
                        }, {
                            "Farea": "0",
                            "Findex": "L",
                            "Fsinger_id": "235",
                            "Fsinger_name": "李克勤",
                            "Fsinger_tag": "555",
                            "Fsort": "104",
                            "Ftrend": "-1",
                            "Ftype": "0",
                        }, {
                            "Farea": "1",
                            "Findex": "Q",
                            "Fsinger_id": "40798",
                            "Fsinger_name": "齐晨",
                            "Fsinger_tag": "555",
                            "Fsort": "105",
                            "Ftrend": "1",
                            "Ftype": "0",
                        }])
                }, 1000)
            },
            _normalizeItems(list) {
                let map = {
                    hot: {
                        title: HOT_NAME,
                        items: []
                    }
                }
                list.forEach((item, index) => {
                    if (index < HOT_SINGER_LEN) {
                        map.hot.items.push({
                            name: item.Fsinger_name,
                            id: item.Fsinger_mid
                        })
                    }
                    const key = item.Findex
                    if (!map[key]) {
                        map[key] = {
                            title: key,
                            items: []
                        }
                    }
                    map[key].items.push({
                        name: item.Fsinger_name,
                        id: item.Fsinger_mid
                    })
                })
                // 为了得到有序列表，我们需要处理 map
                let ret = []
                let hot = []
                for (let key in map) {
                    let val = map[key]
                    if (val.title.match(/[a-zA-Z]/)) {
                        ret.push(val)
                    } else if (val.title === HOT_NAME) {
                        hot.push(val)
                    }
                }
                ret.sort((a, b) => {
                    return a.title.charCodeAt(0) - b.title.charCodeAt(0)
                })
                return hot.concat(ret)
            }
        }
    }

</script>
<style scoped>
.singer{
    position: absolute;
    width: 100%;
    top: 54px;
    left: 0;
    bottom: 0;
}
nav.title{
    height: 44px;
    width: 100%;
    background-color: #ffffff;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
}
.list-group-title{
    background-color: #efefef;
    padding-left: 10px;
}
.list-group-item{
    background-color: #ffffff;
    height: 48px;
    line-height: 48px;
    padding-left: 10px;
    position: relative;
}
.list-group-item:after{
    content: ' ';
    position: absolute;
    bottom: 0;
    left: 0;
    height: 1px;
    background-color: #eee;
    width: 100%;
    -webkit-transform: rotateY(0.5);
    transform: scaleY(0.5);
}
</style>
